[[dev_guide]]
= Developer Guide

This section is for developers who want to fix bugs or change the functionality of the Simple-Kotlin template.

TIP: Read about http://doc.boothub.org/releases/latest/#Templates[writing BootHub templates] before starting to change the Simple-Kotlin template.

The Simple-Kotlin template comes with a suite of tests that generate various skeletons and check their validity.
You should update these tests and add new ones according to the changes you make.

*Command Line Build*

The Simple-Kotlin template is built with http://www.gradle.org[Gradle] and requires JDK 8 or higher.
Clone the GitHub repository, `cd` into the top directory and start the build:

[source]
----
git clone https://github.com/boothub-org/boothub-template-simple-kotlin.git
cd boothub-template-simple-kotlin
./gradlew clean build            (On Windows: gradlew clean build)
----


*IntelliJ Idea*

- start the IntelliJ Idea IDE
- open _build.gradle.kts_


*Eclipse*

- start the Eclipse IDE
- install a recent version of https://projects.eclipse.org/projects/tools.buildship[Buildship]
- import the project using the Gradle Project wizard
