[[getting_started]]
= Getting Started

You can generate a project skeleton based on the Simple-Kotlin template by using the
https://boothub.org/app#/home/true/https%3A%2F%2Fgithub.com%2Fboothub-org%2Fboothub-template-simple-kotlin%2Freleases%2Fdownload%2Fv{project-version}%2Fsimple-kotlin-{project-version}.zip[BootHub GUI, role="external", window="_blank"]
or the
https://boothub.org/app#/cli[BootHub CLI, role="external", window="_blank"].

After providing the http://doc.boothub.org/releases/latest/#template-independent-data[template-independent data], you need to configure the
https://maven.apache.org/guides/mini/guide-naming-conventions.html[Maven groupId] of your project:

++++
<div class="black-background">
<pre class="lime" style="margin-left: 20px;">

Maven groupId: <span class="yellow">org.myproject</span>

</pre>
</div>
<pre>

</pre>
++++

Then you need to configure the artifact ID, the base package and the name of the main class of your application:

++++
<div class="black-background">
<pre class="lime" style="margin-left: 20px;">

Artifact ID [my-project]: ​
Base package [org.myproject]: ​
Application main class name [MyProjectMain]: <span class="yellow">​MyApp</span>

</pre>
</div>
<pre>

</pre>
++++

The next step is to provide information about the project developers:

++++
<div class="black-background">
<pre class="lime" style="margin-left: 20px;">

Developers
Developer ID [jsmith]:
Developer name [John Smith]:
Developer email (optional):
More developers? (Y/N) [N]:

</pre>
</div>
++++

Finally, you need to choose your preferred test framework:

++++
<div class="black-background">
<pre class="lime" style="margin-left: 20px;">

Test Framework:
  1: JUnit 4
  2: JUnit 5
* 3: kotlin.test
  4: Spek
Enter your choice: ​<span class="yellow">​4</span>

</pre>
</div>
++++
